### ISSUE TITLE
Explain Make Json

### ISSUE THREAD

**Issue by itdependsnetworks** [CiscoTestAutomation/getting-started#29]
It is stated `Remember to execute make json every time you create a new parser. ` however, this is not introduced anywhere else (per my search of the pubhub site) and there is no explanation of what it is doing, when to run it (e.g. before or after I write my tests?) 

Can we further explain, and introduce the concept?

**Comment by badalsoyantar** [comment]
PR created.
https://github.com/CiscoTestAutomation/getting-started/pull/33
